[package]
name = "vga"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
bitflags = "1.0"
enum-tryfrom = { version = "0.2.1", default-features = false }
enum-tryfrom-derive = "0.2.1"
